// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzcvqylgahgasmxfcqyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6Y3ZxeWxnYWhnYXNteGZjcXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzIxNjksImV4cCI6MjA2MjIwODE2OX0.1_7NUHSzcMfoLlG8GT-2A53wQH8DkxxyBUa9DihCENM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});