// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdavjmpbvmqzfvitresw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkYXZqbXBidm1xemZ2aXRyZXN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxODkwNzAsImV4cCI6MjA3Nzc2NTA3MH0.4m8gOyNECDYVQMQSgzfEw5nEEJuWDBQWDxHVJFxnxok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});